version: '3.8'

networks:
  default:

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - default

  # nextjs-app:
  #   container_name: nextjs-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #       - 8084:80
  #   expose:
  #       - "8084"
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./nextjs-app:/app
  #     - /app/node_modules
  #     - /app/.next
  #   networks:
  #     - default

volumes: 
  mysql-volume: