import { type GetServerSidePropsContext } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import { getSession } from "next-auth/react";
import { useRouter } from "next/router";
import { z } from "zod";
import { FormProvider } from "@/store/FormProvider";
import { FormNavbar } from "@/components/form";
import { Box, Paper, Card } from "@mui/material";

const isValidID = (uuid: string): boolean => {
  try {
    const data = z.object({ uuid: z.string().uuid() }).parse({ uuid });
    return !!data.uuid;
  } catch (e) {
    return false;
  }
};

export default function Forms() {
  const router = useRouter();
  const { id } = router.query as { id: string };
  const isValidUUID = isValidID(id);

  const { data: formData } = api.form.getPrivateForm.useQuery(
    { id },
    { enabled: isValidUUID },
  );
  console.log("🚀 ~ file: form.tsx:14 ~ Form ~ data:", formData?.data.form);

  if (!formData?.data.form) {
    return <div>error</div>;
  }

  return (
    <>
      <Head>
        <title>FILDER - Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper className="flex min-h-screen flex-col flex-nowrap items-center justify-center gap-4 p-2">
        <FormProvider store={formData.data.form}>
          <FormNavbar />

          <Card className="m-auto h-full w-full">Hello</Card>
        </FormProvider>
      </Paper>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const userSession = await getSession(context);

    if (!userSession?.user?.id)
      return { redirect: { destination: "/", permanent: false } };

    return { props: { userSession } };
  } catch (error) {
    console.error(error);
    return { redirect: { destination: "/", permanent: false } };
  }
}
