name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract version from GitHub run number
        id: extract_version
        run: echo "version=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set up .env file
        run: |
          # echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          # echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          # echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          # echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_PORT=3306" >> .env

      - name: Build Docker image
        run: |
          docker-compose build nextjs-app
          docker tag ${COMPOSE_PROJECT_NAME}_nextjs-app:latest ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.version }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.version }}
